### ISSUE TITLE
Lockscreen artwork sometimes doesn't show

### ISSUE THREAD

**Issue by rejhgadellaa** [rejhgadellaa/icerrr#162]
The first scenario is a known issue: you need to have at least one starred station for the feature to work to begin with.

The second is probably because the metadata is only updated when the nowplaying variable changes.

**Comment by PanderMusubi** [comment]
Please, use the black and white radio image as default, not a huge version of the app icon as is currently the case / showing on Android 5.1.1.

**Comment by rejhgadellaa** [comment]
Hmm there is an option to disable that in Settings.. But you're asking to
turn that off by default..?

Roderick Gadellaa (mobile)

**Comment by PanderMusubi** [comment]
The image shown is large version of headset, not the radio photograph.

**Comment by rejhgadellaa** [comment]
Ah that one. Yeah that's the fallback, makes sense to hide it. For_future
but shouldn't be too much of a hassle so I expect it to be done soon.

**Comment by PanderMusubi** [comment]
I think this one is fixed. Correct?

**Comment by rejhgadellaa** [comment]
Correct ;)
