### ISSUE TITLE
Options for no downloadable artwork and station icon at all

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#172]
Please offer a setting in which no artwork is being used, except the nice background picture of the old radio dial.

This option will save on downloads but also on missing icons for streams, see first screenshot. Here I prefer no icon/artwork over the very nice background. No changes are needed for the text that is displayed.

![screenshot_2015-03-19-17-53-54](https://cloud.githubusercontent.com/assets/198964/6738447/7659bd46-ce72-11e4-91bd-623d7f1851f6.png)

Secondly, this option will prevent locked screen artwork that might be considered NSFW, or artwork misidentified as NSFW while it is not, see the second screenshot.

![screenshot_2015-03-19-17-53-46](https://cloud.githubusercontent.com/assets/198964/6738448/765afad0-ce72-11e4-945b-7c14f0dcb279.png)

**Comment by rejhgadellaa** [comment]
Will have a look. Shouldn't be too hard to implement :)

**Comment by rejhgadellaa** [comment]
Option added under Settings in v0.208 (available now)
