### ISSUE TITLE
Adding station manually doesn't work

### ISSUE THREAD

**Issue by pstraszak** [rejhgadellaa/icerrr#174]
I tried to add station by hand. It saved the station but when try to start playing it's not working.
I figured out what happend: it adds "/;" at the end of the Station url.

Example:
I tried to add station from url: http://195.150.20.242:8000/rmf_fm
After save I have in url: http://195.150.20.242:8000/rmf_fm/;

Workarround:
Add question mark at the end of url while adding new station. Still after save I have "/;" added at the end but radio is working.
Example: http://195.150.20.242:8000/rmf_fm?

**Comment by rejhgadellaa** [comment]
Thanks for the report I'll look into it
