### ISSUE TITLE
Workout new color palette

### ISSUE THREAD

**Issue by rejhgadellaa** [rejhgadellaa/icerrr#205]
Currently testing with:
https://www.materialpalette.com/blue-grey/deep-orange

**Comment by PanderMusubi** [comment]
Please ship material design launcher icon that is only white on background color of your choice. No shading or other effects.

**Comment by rejhgadellaa** [comment]
Hmmmm.. I'll have to look if that is even possible.. It means replacing an image that is packaged in the resources folder (not www assets). I'll make a separate issue out of this.

**Comment by rejhgadellaa** [comment]
@PanderMusubi plz see #210
