### ISSUE TITLE
Feature listing

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#216]
Add a feature listing to the website with information such as:
  * stream management: add, edit, remove favorite
  * stream playback: play, pause, stop, next
  * ...

**Comment by rejhgadellaa** [comment]
You mean on the landing page? Or in the readme here on github? (which I kind of use for "more info" right now)

**Comment by PanderMusubi** [comment]
Both!

**Comment by PanderMusubi** [comment]
Icerrr currently supports:
* audio stream playback: play, pause, stop, next
* audio stream as alarm: add, repeat, edit, remove
* audio stream management: add via Dirble, edit, favorite
* audio stream formats: MP3, PLS, M3U
* audio streaming: Chromecast
* audio scrobbling: Last.fm, Libre.fm
* look and feel: Material Design
* customization: force WiFi, force speaker
* artwork: now playing album art, stream icon, lock screen
* sleep tracking integration: Sleep as Android (hence Phillips Hue)
* settings management: auto upgrade, JSON export, JSON import

I had
* audio stream formats: MP3 (audio/mpeg), PLS (audio/x-scpls), M3U (application/x-mpegurl)

but that is too technical, so better what is proposed above. Also, do not mention no support for AAC. It will be listed once it is supported. All text is written as short as possible and the order of the bullets is also carefully set.

Note: You use a lot the word "station". In general, talk about about (audio) stream. Streams are not always music, can also be spoken word or from a live event or seminar. A station is something such as "SomaFM" or "Intergalactic FM". A channel is more what relates to an audio stream such as "3FM".

Until you have a hierarchical storage of stations and channels, I would simply only refer to "stream".

**Comment by rejhgadellaa** [comment]
Thanks!

I forgot icerrr also supports wma streams so I'll add that one.

Stations: hmm true but a 'station' may contain multiple streams (hq, lq). Will think about it :)

**Comment by PanderMusubi** [comment]
Then the hierarchy would be station, channel, stream.

**Comment by PanderMusubi** [comment]
Looking forward seeing the features overview on your web page. 

PS  Have you considered offering a Flattr button here and on your website?

**Comment by rejhgadellaa** [comment]
Feature list now available on (brand new) landing page :D

**Comment by rejhgadellaa** [comment]
Right, the url: www.rejh.nl/icerrt
