### ISSUE TITLE
List of more stations and channels to add

### ISSUE THREAD

**Issue by PanderMusubi** [rejhgadellaa/icerrr#37]
add studio brussel and much much more from
http://www.hendrikjansen.nl/henk/streaming.html

here are also streams of lower quality for less data traffic
http://mp3.streampower.be/status.xsl

**Comment by confact** [comment]
@PanderMusubi I am the owner or Dirble, the directory Icerr use. You can add your station yourself at https://dirble.com/addstation - the thing it is impossible to add all stations all people want, so the best scenario is that you add the station you want yourself on Dirble. I hope that is a good answer enough. 
icerr can't control which stations Dirble have.

**Comment by PanderMusubi** [comment]
OK, thanks. I will check if I can add some stations there. I know the author of Icerrr personally and he usually implements feature requests coming from me. Was trying to think out was which are generating some support in a commercial or pro version of of Icerrr.

**Comment by rejhgadellaa** [comment]
Studio Brussels is available on Dirble, users can add it via search.
